---
- name: 'Create persistent folders'
  file:
    path: '{{ role_blog_docker_host_dir }}/{{ item }}'
    state: 'directory'
  loop:
    - 'docker'
    - 'data'
    - 'data/public'
  tags:
    - 'blog:filesystem'

# - name: 'copy hugo config'
#   copy:
#     src: 'files/config.yaml'
#     dest: '{{ role_blog_docker_host_dir }}/docker/config.yaml'
#     owner: 'root'
#     group: 'root'
#   tags:
#     - 'blog:filesystem'

- name: 'copy hugo content'
  copy:
    src: 'files/blog/public/'
    dest: '{{ role_blog_docker_host_dir }}/data/public'
    owner: 'root'
    group: 'root'
  tags:
    - 'blog:filesystem'
...
