---
baseURL: 'https://blog.dhoessl.de/'
languageCode:
  - 'en-us'
  - 'de-de'
defaultContentLanguage: 'de'
defaultContentLanguageInSubdir: true
languages:
  en:
    title: 'dhoessl.de'
    contentDir: 'content/english'
    languageName: 'English'
    menu:
      main:
        - identifier: 'categories'
          name: 'Categories'
          url: '/categories/'
          weight: 10
        - identifier: 'tags'
          name: 'Tags'
          url: '/tags/'
          weight: 20
        - identifier: 'search'
          name: 'Search'
          url: '/search/'
          weight: 30
    params:
      homeInfoParams:
        Title: "Hello There \U0000270C\U0001F3FC"
        Content: ''
    weight: 2
  de:
    title: 'dhoessl.de'
    contentDir: 'content/german'
    languageName: 'Deutsch'
    menu:
      main:
        - identifier: 'categories'
          name: 'Kategorien'
          url: '/categories/'
          weight: 10
        - identifier: 'tags'
          name: 'Tags'
          url: '/tags/'
          weight: 20
        - identifier: 'search'
          name: 'Suche'
          url: '/search/'
          weight: 30
    params:
      homeInfoParams:
        Title: "Servus \U0000270C\U0001F3FC dhoessl hier"
        Content: ''
    weight: 1

theme:
  - 'PaperMod'
paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  # to enable google analytics, opengraph, twitter-cards and schema.
  env: 'production'
  title: 'Dhoessl Blog'
  description: 'Dhoessl Blog'
  keywords:
    - 'Blog'
    - 'PaperMod'
  author: 'dhoessl'
  # images: [ '<link or path of image for opengraph, twitter-cards>' ]
  DateFormat: 'January 2, 2006'
  defaultTheme: 'dark'  # light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true
    # disableFingerprinting: true
    favicon: '/fav_192_192.ico'
    favicon16x16: '/fav_32_32.ico'
    favicon32x32: '/fav_16_16.ico'
    # apple_touch_icon: '<link / abs url>'
    # safari_pinned_tab: '<link / abs url>'

  socialIcons:
    - name: 'github'
      url: 'https://github.com/dhoessl'
    - name: 'instagram'
      url: 'https://www.instagram.com/dhoessl/'

  cover:
    hidden: true  # hide everywhere but not in structured data
    hiddenInList: true  # hide on list pages and home
    hiddenInSingle: true  # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - 'title'
      - 'permalink'
      - 'summary'
      - 'content'

outputs:
  home:
    - 'HTML'
    - 'RSS'
    - 'JSON'
...
